CREATE DATABASE PinkanelDB;

CREATE TABLE Player
(
  ID_Player INT  AUTO_INCREMENT NOT NULL,
  Name varchar(20) NOT NULL,
  Surname varchar(20) NOT NULL,
  PRIMARY KEY (ID_Player)
);

CREATE TABLE Games
(
  ID_Game INT AUTO_INCREMENT NOT NULL,
  StartTime DATE NOT NULL,
  Score1 INT NOT NULL,
  Score2 INT NOT NULL,
  PRIMARY KEY (ID_Game)
);

CREATE TABLE Dots
(
  ID_Dot INT AUTO_INCREMENT NOT NULL,
  X INT NOT NULL,
  Y INT NOT NULL,
  T TIMESTAMP(6),
  ID_Game INT NOT NULL,
  PRIMARY KEY (ID_Dot),
  FOREIGN KEY (ID_Game) REFERENCES Games(ID_Game)
);

CREATE TABLE Play
(
  ID_Game INT NOT NULL,
  ID_Player1 INT NOT NULL,
  ID_Player2 INT NOT NULL,
  PRIMARY KEY (ID_Game, ID_Player1, ID_Player2),
  FOREIGN KEY (ID_Player1) REFERENCES Player(ID_Player),
  FOREIGN KEY (ID_Player2) REFERENCES Player(ID_Player),
  FOREIGN KEY (ID_Game) REFERENCES Games(ID_Game)
);
